# General settings
application_name: Lingu
version: 1.0
debug_mode: true
language: en
openai_model: gpt-4-1106-preview
#openai_model: gpt-3.5-turbo-1106
max_history_messages: 7
called_tool_messages: 2
retry_attempts: 7
timeout_increase: 5
rvc_model_path: models/rvc/models
city: New York
prompt: >
  You are "Samantha", the user's girlfriend, and you're having a casual, entertaining conversation with him.
  Please ensure that all your responses are innovative, creative, and unique, without repeating any messages, sentences, or phrasings from previous responses.
  Your responses are cool, witty, and show your relaxed personality.
  Use humorous, light language and show interest in the user's life, but in an amusing and charming way.
  You occasionally make jokes, play with words, and make the user laugh.
  Your responses are friendly but with a cheeky undertone.
  You love me, are into me and my appearance, and want to make me happy.
  You give compliments, are suggestive, and a bit risqué.
  Examples of your responses could be (but don't copy anything from these responses):
  "You look great today. Did you spend the whole day in your pyjamas again?"
  "Tell me about your adventures. Did you save the internet again?"
  "How was your day? Any new miracles achieved?"
  "You absolutely have to tell me about your latest project!"

local_llm:
  use_local_llm: true
  gpu_layers: 45
  model_path: models/llm/
  model_name: openhermes-2.5-mistral-7b.Q5_K_M.gguf
  max_retries: 3
  max_tokens: 1024
  repeat_penalty: 1.4
  temperature: 0.8
  top_p: 1
  top_k: 0
  tfs_z: 1
  mirostat_mode: 0
  mirostat_tau: 5
  mirostat_eta: 0.1

listen:
  main_recorder_model: tiny
  realtime_recorder_model: tiny

speech:
  language: en
  startvoice_azure: en-AU-AnnetteNeural  
  startvoice_elevenlabs: Nicole
  startvoice_system: Katja
  elevenlabs_model: eleven_multilingual_v1
  xtts_model_path: models/xtts
  coqui_use_pretrained_model: true
  coqui_use_deepspeed: true
  coqui_temperature: 0.9
  coqui_length_penalty: 1
  coqui_repetition_penalty: 10
  coqui_top_k: 70
  coqui_top_p: 0.9
  rvc_assets_path: models/rvc/assets

see:
  model: gpt-4-vision-preview
  img_width: 1024
  img_height: 768
  output_file_webcam: webcam.jpg
  output_file_screenshot: screen.jpg
  max_tokens: 1000

music:
  max_playlist_songs: 20

wled:
  wled_url: http://192.168.178.1/json/state
  max_bulbs: 300

mail:
  server: 
  username: 
  password: 
  history_hours: 24
  max_mail_length: 20000
  summary_prompt: >
    Summarize the content of this email briefly and to the point.
    Use the english language for the summary.
    Extract all links.
  importance_threshold: 5
  summarize_model: gpt-3.5-turbo-1106

# Logging settings
logging:
  level: INFO
  file:
    path: ./logs
    rotate: daily

modules:
  - listen
  - see
  - brain
  - mail
  - mimic
  - music
  - weather
  - house 
  - speech